// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDti-0kUOi45WnwrqdR9o9ShkhlVW7yOf4',
    appId: '1:179827471301:web:5dece2542cdb21846011ac',
    messagingSenderId: '179827471301',
    projectId: 'social-3500e',
    authDomain: 'social-3500e.firebaseapp.com',
    storageBucket: 'social-3500e.appspot.com',
    measurementId: 'G-34SQQCXGBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxNCYBE2IOC9KxLhXfh3XvQX6FZAl5tfE',
    appId: '1:179827471301:android:330525179a839db16011ac',
    messagingSenderId: '179827471301',
    projectId: 'social-3500e',
    storageBucket: 'social-3500e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2RyB2G6snCfnNLPxwaCGqy9jQGuxaNA',
    appId: '1:179827471301:ios:313457a3f1c9b01c6011ac',
    messagingSenderId: '179827471301',
    projectId: 'social-3500e',
    storageBucket: 'social-3500e.appspot.com',
    iosBundleId: 'com.example.socialChats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR2RyB2G6snCfnNLPxwaCGqy9jQGuxaNA',
    appId: '1:179827471301:ios:1a83a4109b90653c6011ac',
    messagingSenderId: '179827471301',
    projectId: 'social-3500e',
    storageBucket: 'social-3500e.appspot.com',
    iosBundleId: 'com.example.socialChats.RunnerTests',
  );
}
